// Code generated by cmd/gentypes from internal/dto, internal/registry, and
// cmd/go-red/websocket. DO NOT EDIT — run `go generate ./internal/dto/...`
// (or `make generate-types`) to regenerate after changing those packages.

export type MessageType = 'flow:list' | 'flow:get' | 'flow:create' | 'flow:update' | 'flow:delete' | 'flow:deploy' | 'flow:undeploy' | 'flow:status' | 'node:add' | 'node:remove' | 'node:update' | 'node:config' | 'node:status' | 'connection:add' | 'connection:remove' | 'message:send' | 'message:log' | 'error' | 'info' | 'ping' | 'pong' | 'state:sync' | '*';

export type FlowStatus = 'draft' | 'running' | 'error' | 'deploying' | 'undeploying';

export interface Position {
  x: number;
  y: number;
}

export interface NodeStatus {
  state: string;
  message?: string;
  timestamp?: string;
  processingCount?: number;
  errorCount?: number;
}

export interface Node {
  id: string;
  type: string;
  name?: string;
  position: Position;
  config: Record<string, any>;
  status: NodeStatus;
  disabled: boolean;
}

export interface Connection {
  id: string;
  sourceNode: string;
  sourcePort?: string;
  targetNode: string;
  targetPort?: string;
}

export interface RetryPolicy {
  maxRetries: number;
  backoff: number;
  maxBackoff: number;
  retryOn: string[];
}

export interface FlowConfig {
  timeout: number;
  maxConcurrency: number;
  retryPolicy: RetryPolicy;
  environment: Record<string, string>;
}

export interface Flow {
  id: string;
  name: string;
  description: string;
  nodes: Record<string, Node>;
  connections: Connection[];
  status: FlowStatus;
  config: FlowConfig;
  createdAt: string;
  updatedAt: string;
  version: string;
}

export interface FlowSummary {
  id: string;
  name: string;
  description?: string;
  status: FlowStatus;
  nodeCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface FlowCreateRequest {
  id?: string;
  name: string;
  description?: string;
}

export interface FlowUpdateRequest {
  name?: string;
  description?: string;
  nodes?: Record<string, Node>;
  connections?: Connection[];
  config?: FlowConfig;
}

export interface Message {
  id: string;
  flowId: string;
  payload: Record<string, any>;
  metadata: Record<string, string>;
  path: string[];
  timestamp: string;
}

export interface Port {
  id: string;
  name: string;
  description: string;
  required: boolean;
}

export interface Property {
  type: string;
  description: string;
  default: any;
  enum: string[];
  min?: number;
  max?: number;
  pattern: string;
}

export interface Schema {
  properties: Record<string, Property>;
  required: string[];
}

export interface NodeMetadata {
  id: string;
  type: string;
  name: string;
  description: string;
  category: string;
  inputs: Port[];
  outputs: Port[];
  configSchema: Schema;
  icon: string;
  tags: string[];
}

export interface WebSocketMessage {
  type: MessageType;
  data: any;
  timestamp: string;
  requestId?: string;
}
