// Code generated by cmd/gentypes from internal/dto, internal/registry, and
// cmd/go-red/websocket. DO NOT EDIT — run `go generate ./internal/dto/...`
// (or `make generate-types`) to regenerate after changing those packages.

export type MessageType = 'flow:list' | 'flow:get' | 'flow:delete' | 'flow:status' | 'subscribe' | 'unsubscribe' | 'flow:snapshot' | 'node:status' | 'debug:message' | 'flow:metrics' | 'message:send' | 'error' | 'info' | 'ping' | 'pong' | 'state:sync' | '*';

export type FlowStatus = 'draft' | 'running' | 'error' | 'deploying' | 'undeploying';

export interface Position {
  x: number;
  y: number;
}

export interface Node {
  id: string;
  type: string;
  name?: string;
  position: Position;
  config: Record<string, any>;
  disabled: boolean;
}

export interface Connection {
  id: string;
  sourceNode: string;
  sourcePort?: string;
  targetNode: string;
  targetPort?: string;
}

export interface RetryPolicy {
  maxRetries: number;
  backoff: number;
  maxBackoff: number;
  retryOn: string[];
}

export interface FlowConfig {
  timeout: number;
  maxConcurrency: number;
  retryPolicy: RetryPolicy;
  environment: Record<string, string>;
}

export interface Flow {
  id: string;
  name: string;
  description: string;
  nodes: Record<string, Node>;
  connections: Connection[];
  status: FlowStatus;
  config: FlowConfig;
  createdAt: string;
  updatedAt: string;
  deployedAt?: string;
  version: string;
}

export interface FlowSummary {
  id: string;
  name: string;
  description?: string;
  status: FlowStatus;
  nodeCount: number;
  createdAt: string;
  updatedAt: string;
  deployedAt?: string;
}

export interface FlowCreateRequest {
  id?: string;
  name: string;
  description?: string;
}

export interface FlowUpdateRequest {
  name?: string;
  description?: string;
  nodes?: Record<string, Node>;
  connections?: Connection[];
  config?: FlowConfig;
}

export interface Message {
  id: string;
  flowId: string;
  payload: Record<string, any>;
  metadata: Record<string, string>;
  path: string[];
  timestamp: string;
}

export interface DeployResponse {
  flowId: string;
  status: FlowStatus;
  updatedAt?: string;
  deployedAt?: string;
  message?: string;
}

export interface ErrorResponse {
  error: string;
}

export interface FlowStatusEvent {
  flowId: string;
  status: FlowStatus;
  updatedAt?: string;
  deployedAt?: string;
  error?: string;
}

export interface NodeStatus {
  fill?: string;
  shape?: string;
  text?: string;
  timestamp?: string;
}

export interface NodeStatusEvent {
  flowId: string;
  nodeId: string;
  status: NodeStatus;
}

export interface DebugMessage {
  id: string;
  flowId: string;
  nodeId: string;
  nodeName?: string;
  nodeType?: string;
  level: string;
  topic?: string;
  payload: any;
  timestamp: string;
}

export interface NodeMetrics {
  messages: number;
  errors: number;
}

export interface FlowMetricsEvent {
  flowId: string;
  nodes: Record<string, NodeMetrics>;
  timestamp: string;
}

export interface FlowSnapshot {
  flowId: string;
  status: FlowStatus;
  nodeStatus: Record<string, NodeStatus>;
  metrics: Record<string, NodeMetrics>;
  debug: DebugMessage[];
}

export interface SubscribeRequest {
  flowId: string;
}

export interface Port {
  id: string;
  name: string;
  description: string;
  required: boolean;
}

export interface Property {
  type: string;
  description: string;
  default: any;
  enum: string[];
  min?: number;
  max?: number;
  pattern: string;
}

export interface Schema {
  properties: Record<string, Property>;
  required: string[];
}

export interface NodeMetadata {
  id: string;
  type: string;
  name: string;
  description: string;
  category: string;
  inputs: Port[];
  outputs: Port[];
  configSchema: Schema;
  icon: string;
  tags: string[];
}

export interface WebSocketMessage {
  type: MessageType;
  data: any;
  timestamp: string;
  requestId?: string;
}
