/**
 * Icon vocabulary of the editor (docs/NEXT_LEVEL_PLAN.md, Phase 4): the
 * backend names an icon (`NodeMetadata.icon: "timer"`), the frontend
 * renders it from Lucide. Only icons listed here ship in the bundle; an
 * unknown name falls back to the node's category icon.
 */
import {
  Activity,
  AlarmClock,
  Antenna,
  ArrowDownAZ,
  ArrowLeftRight,
  Boxes,
  Braces,
  Bug,
  Cable,
  CircleCheck,
  CircleDot,
  CirclePlay,
  CloudDownload,
  Code,
  CodeXml,
  Database,
  Eye,
  FileCode,
  FileInput,
  FileText,
  Filter,
  GitBranch,
  Globe,
  Hash,
  Layers,
  LifeBuoy,
  ListTree,
  Lock,
  LogIn,
  LogOut,
  Merge,
  MessageSquare,
  Network,
  Plug,
  PlugZap,
  Puzzle,
  Radio,
  RadioTower,
  Regex,
  Replace,
  Reply,
  Route,
  Satellite,
  SatelliteDish,
  Save,
  Scissors,
  ScrollText,
  Send,
  Server,
  Settings,
  Shield,
  SlidersHorizontal,
  Table,
  Terminal,
  Timer,
  Waypoints,
  Wifi,
  type LucideIcon,
} from 'lucide-react';

/** Icons a node type may ask for by name. */
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  antenna: Antenna,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-left-right': ArrowLeftRight,
  boxes: Boxes,
  braces: Braces,
  bug: Bug,
  cable: Cable,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-play': CirclePlay,
  'cloud-download': CloudDownload,
  code: Code,
  'code-xml': CodeXml,
  database: Database,
  eye: Eye,
  'file-code': FileCode,
  'file-input': FileInput,
  'file-text': FileText,
  filter: Filter,
  'git-branch': GitBranch,
  globe: Globe,
  hash: Hash,
  layers: Layers,
  'life-buoy': LifeBuoy,
  'list-tree': ListTree,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  merge: Merge,
  'message-square': MessageSquare,
  network: Network,
  plug: Plug,
  'plug-zap': PlugZap,
  puzzle: Puzzle,
  radio: Radio,
  'radio-tower': RadioTower,
  regex: Regex,
  replace: Replace,
  reply: Reply,
  route: Route,
  satellite: Satellite,
  'satellite-dish': SatelliteDish,
  save: Save,
  scissors: Scissors,
  'scroll-text': ScrollText,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  'sliders-horizontal': SlidersHorizontal,
  table: Table,
  terminal: Terminal,
  timer: Timer,
  waypoints: Waypoints,
  wifi: Wifi,
};

/** Fallback icon per node category. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  input: LogIn,
  output: LogOut,
  function: Code,
  'flow-control': Waypoints,
  storage: Database,
  network: Globe,
  protocol: Cable,
  parser: FileCode,
  social: MessageSquare,
  config: Settings,
  dashboard: Activity,
  custom: Puzzle,
};

export function iconByName(name?: string): LucideIcon | undefined {
  return name ? ICONS[name] : undefined;
}

export function categoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category] || CATEGORY_ICONS.custom;
}
